# Default values for knative-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
# appVersion: "1.0.0"

service:
  image:
    repository: nginxinc/nginx-unprivileged
    pullPolicy: Always
    tag: ""
  # livenessProbe:
  #   httpGet:
  #     port: 8080
  #     path: /actuator/health/liveness
  #   initialDelaySeconds: 30
  port: 8080
  # resources: 
  #   limits:
  #     cpu: 300m
  #     memory: 512Mi
  #   requests:
  #     cpu: 10m
  #     memory: 480Mi


customDomains: []
#  - url: test.app.com