apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "knative-application.fullname" . }}
  labels:
    {{- include "knative-application.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "knative-application.labels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.service.livenessProbe | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
          {{- toYaml .Values.service.resources | nindent 12 }}
